steps:
  # Install dependencies
  - name: 'node:16'  # or the node version your project uses
    entrypoint: 'npm'
    args: ['install']

  # Run tests
  - name: 'node:16'
    entrypoint: 'npm'
    args: ['run', 'test']  # Assuming you have a script named "test" in package.json

  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/causal-bongo-436119-m3/my-app', '.']

  # Push Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/causal-bongo-436119-m3/my-app']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'my-app', '--image', 'gcr.io/causal-bongo-436119-m3/my-app', '--platform', 'managed', '--region', 'us-central1']

timeout: '1200s'
